name: Regression-with-an-Insurance-Dataset
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12.3
  - pandas
  - numpy
  - numba
  - scikit-learn
  - matplotlib
  - seaborn
  - ipython
  - ipykernel
  - catboost
  - ipywidgets